/*
	SDZService_Mobile.h
	The interface definition of classes and methods for the Service_Mobile web service.
	Generated by SudzC.com
*/
				
#import "Soap.h"
	
/* Add class references */
				
#import "SDZStructuralObject.h"
#import "SDZArrayOfvw_ExpenseType.h"
#import "SDZArrayOfvw_state.h"
#import "SDZArrayOfvw_country.h"
#import "SDZArrayOfvw_payMethod.h"
#import "SDZArrayOfvw_jobList.h"
#import "SDZArrayOfvw_currency.h"
#import "SDZArrayOfvw_vendor.h"
#import "SDZEntityObject.h"
#import "SDZArrayOfEntityKeyMember.h"
#import "SDZEntityKeyMember.h"
#import "SDZvw_vendor.h"
#import "SDZArrayOfstring.h"
#import "SDZvw_UnSubmitedBankTranx.h"
#import "SDZArrayOfvw_UnSubmitedBankTranx.h"

#import "SDZEntityKey.h"
#import "SDZvw_ExpenseType.h"
#import "SDZvw_state.h"
#import "SDZvw_country.h"
#import "SDZvw_payMethod.h"
#import "SDZvw_jobList.h"
#import "SDZvw_currency.h"
#import "SDZFileTransferRequestBuf.h"
#import "SDZFileReceivedInfoBuf.h"
#import "SDZvw_GetConfigLablesInfo.h"
#import "SDZvw_GetApplicationConfigLables.h"
#import "SDZvw_ReportType.h"
#import "SDZArrayOfvw_ReportType.h"
#import "SDZHeaderConfigLabelInfo.h"
#import "SDZArrayOfHeaderConfigLabelInfo.h"
#import "SDZvw_Class.h"
#import "SDZArrayOfvw_classList.h"
#import "SDZService_GetSettings.h"
#import "SDZArrayOfvw_GetSettings.h"
#import "SDZArrayOfvw_GetMileageAddress.h"
#import "SDZArrayOfvw_GetSettings.h"
#import "SDZService_GetMileageAddressMatrixList.h"
#import "SDZArrayOfvw_GetMileageAddressMatrixList.h"
#import "SDZService_GetMileageAddress.h"

#import "SDZvw_CostAccountings.h"
#import "SDZArrayOfvw_CostAccountings.h"
#import "SDZvw_CostCenters.h"
#import "SDZArrayOfvw_CostCenters.h"
#import "SDZArrayOfvw_BusinessUnits.h"
#import "SDZArrayOfvw_BusinessUnits.h"
#import "SDZvw_CostCompanies.h"
#import "SDZArrayOfvw_CostCompanies.h"

#import "SDZvw_CostAccountings.h"
#import "SDZArrayOfvw_CostAccountings.h"
#import "SDZArrayOfvw_CostCenters.h"
#import "SDZvw_CostCenters.h"
#import "SDZArrayOfvw_BusinessUnits.h"
#import "SDZvw_BusinessUnits.h"
#import "SDZArrayOfvw_CostCompanies.h"
#import "SDZvw_CostCompanies.h"
#import <CoreData/CoreData.h>

/* Interface for the service */
				
@interface SDZService_Mobile : SoapService
		
	/* Returns BOOL.  */
	- (SoapRequest*) Create: (id <SoapDelegate>) handler UserId: (NSNumber *) UserId CurrencyId: (int) CurrencyId VendorName: (NSString*) VendorName ExpenseTypeId: (int) ExpenseTypeId Amount: (NSDecimalNumber*) Amount City: (NSString*) City Comment: (NSString*) Comment ConvertedAmount: (NSDecimalNumber*) ConvertedAmount CurrencyRate: (NSDecimalNumber*) CurrencyRate ExpenseDate: (NSDate*) ExpenseDate TransactionName: (NSString*) TransactionName TransactionSource: (NSString*) TransactionSource Active: (BOOL) Active NotReimbursable: (BOOL) NotReimbursable ReceiptPath: (NSString*) ReceiptPath IsReceipt: (int) IsReceipt CountryId: (int) CountryId StateId: (int) StateId PayMethodId:(int)payMethodId Activity: (NSString*) Activity CoWorkers: (NSString*) CoWorkers OtherComments: (NSString*) OtherComments;


- (SoapRequest*) Create: (id) _target action: (SEL) _action UserId: (NSNumber *) UserId CurrencyId: (int) CurrencyId VendorName: (NSString*) VendorName ExpenseTypeId: (int) ExpenseTypeId Amount: (NSDecimalNumber*) Amount City: (NSString*) City Comment: (NSString*) Comment ConvertedAmount: (NSDecimalNumber*) ConvertedAmount CurrencyRate: (NSDecimalNumber*) CurrencyRate ExpenseDate: (NSDate*) ExpenseDate TransactionName: (NSString*) TransactionName TransactionSource: (NSString*) TransactionSource Active: (BOOL) Active NotReimbursable: (BOOL) NotReimbursable ReceiptPath: (NSString*) ReceiptPath IsReceipt: (int) IsReceipt CountryId: (int) CountryId StateId: (int) StateId PayMethodId:(int)PayMethodId Activity: (NSString*) Activity CoWorkers: (NSString*) CoWorkers OtherComments: (NSString*) OtherComments OtherAmount1: (NSDecimalNumber*) OtherAmount1 OtherAmount2: (NSDecimalNumber*) OtherAmount2 OtherAmount3: (NSDecimalNumber*) OtherAmount3 OtherAmount4: (NSDecimalNumber*) OtherAmount4 withBP:(NSString*)BusinessP customerID:(int)custID ProjectID:(int)projID TaskID:(int)taskId CompanyId:(int)companyId BusinessUnitID:(int)businessUnitId CostCenterId:(int)costCenterId BillingId:(int)billingId violationID:(int)violationID referenceType:(NSString *)referenceTYpe withDetailID:(int)expenseDetailID ReceiptViolationID:(int)ReceiptViolationID OCRDict:(NSMutableDictionary *)ocrDict withBusinessActivityID:(int)BusinessActivityID withReferenceID:(int)ReferenceID withStaffMemberID:(int)StaffMemberID withApproverID:(int)ApproverID;


- (SoapRequest*) Update: (id <SoapDelegate>) handler UserId: (NSNumber *) UserId CurrencyId: (int) CurrencyId VendorName: (NSString*) VendorName ExpenseTypeId: (int) ExpenseTypeId Amount: (NSDecimalNumber*) Amount City: (NSString*) City Comment: (NSString*) Comment ConvertedAmount: (NSDecimalNumber*) ConvertedAmount CurrencyRate: (NSDecimalNumber*) CurrencyRate ExpenseDate: (NSDate*) ExpenseDate TransactionName: (NSString*) TransactionName TransactionSource: (NSString*) TransactionSource Active: (BOOL) Active NotReimbursable: (BOOL) NotReimbursable ReceiptPath: (NSString*) ReceiptPath IsReceipt: (int) IsReceipt CountryId: (int) CountryId StateId: (int) StateId
            PayMethodId:(int)PayMethodId Activity: (NSString*) Activity CoWorkers: (NSString*) CoWorkers OtherComments: (NSString*) OtherComments ExpenseDetailId : (NSDecimalNumber *)ExpenseDetailId ;


- (SoapRequest*) Update: (id) _target action: (SEL) _action UserId: (NSNumber *) UserId CurrencyId: (int) CurrencyId VendorName: (NSString*) VendorName ExpenseTypeId: (int) ExpenseTypeId Amount: (NSDecimalNumber*) Amount City: (NSString*) City Comment: (NSString*) Comment ConvertedAmount: (NSDecimalNumber*) ConvertedAmount CurrencyRate: (NSDecimalNumber*) CurrencyRate ExpenseDate: (NSDate*) ExpenseDate TransactionName: (NSString*) TransactionName TransactionSource: (NSString*) TransactionSource Active: (BOOL) Active NotReimbursable: (BOOL) NotReimbursable ReceiptPath: (NSString*) ReceiptPath IsReceipt: (int) IsReceipt CountryId: (int) CountryId StateId: (int) StateId PayMethodId:(int)PayMethodId Activity: (NSString*) Activity CoWorkers: (NSString*) CoWorkers OtherComments: (NSString*) OtherComments OtherAmount1: (NSDecimalNumber*) OtherAmount1 OtherAmount2: (NSDecimalNumber*) OtherAmount2 OtherAmount3: (NSDecimalNumber*) OtherAmount3 OtherAmount4: (NSDecimalNumber*) OtherAmount4 ExpenseDetailId : (NSDecimalNumber *)ExpenseDetailId BusinessPurpose:(NSString *) BusinessP customerID:(int)custID ProjectID:(int)projID TaskID:(int)taskId CompanyId:(int)companyId BusinessUnitID:(int)businessUnitId CostCenterId:(int)costCenterId BillingId:(int)billingId violationID:(int)violationID referenceType:(NSString *)referenceTYpe withDetailID:(int)expenseDetailID ReceiptViolationID:(int)ReceiptViolationID OCRDict:(NSMutableDictionary *)ocrDict withBusinessActivityID:(int)BusinessActivityID withReferenceID:(int)ReferenceID withStaffMemberID:(int)StaffMemberID withApproverID:(int)ApproverID;

	/* Returns NSString*.  */
	- (SoapRequest*) UploadFileDefault: (id <SoapDelegate>) handler sourceStream: (NSData*) sourceStream;
	- (SoapRequest*) UploadFileDefault: (id) target action: (SEL) action sourceStream: (NSData*) sourceStream;

	/* Returns SDZFileReceivedInfoBuf*.  */
	- (SoapRequest*) UploadFileBuffered: (id <SoapDelegate>) handler request: (SDZFileTransferRequestBuf*) request;
	- (SoapRequest*) UploadFileBuffered: (id) target action: (SEL) action request: (SDZFileTransferRequestBuf*) request;

	/* Returns BOOL.  */
	- (SoapRequest*) UploadFile: (id <SoapDelegate>) handler Data: (NSData*) Data UploadFolder:(NSString *)UploadFolder fileFormat:(NSString *)fileFormat;
- (SoapRequest*) UploadFile: (id) target action: (SEL) action Data: (NSData*) Data UploadFolder:(NSString *)UploadFolder fileFormat:(NSString *)fileFormat;

//vai
- (SoapRequest*) getPendingList: (id) _target action: (SEL) _action UserId: (NSNumber *) UserId;
- (SoapRequest*) removeReceiptFromBox: (id) _target action: (SEL) _action UserId: (NSNumber *) UserId ReceiptId: (NSNumber *) ReceiptId;
- (SoapRequest*) UploadReceipt: (id) _target action: (SEL) _action Data: (NSData*) Data UploadFolder: (NSString *)UploadFolder fileFormat:(NSString *)fileFormat;

- (SoapRequest*) GetAppSettings: (id <SoapDelegate>) handler UserId: (NSNumber *) UserId;
- (SoapRequest*) GetAppSettings: (id) target action: (SEL) action UserId: (NSNumber *) UserId;

	/* Returns NSMutableArray*.  */
	- (SoapRequest*) GetVendorList: (id <SoapDelegate>) handler UserId: (NSNumber *) UserId;
	- (SoapRequest*) GetVendorList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;

- (SoapRequest*) GetCoWorkersList: (id <SoapDelegate>) handler UserId: (NSNumber *) UserId;
- (SoapRequest*) GetCoWorkersList: (id) _target action: (SEL) _action UserId: (NSNumber *) UserId;

	/* Returns NSMutableArray*.  */
	- (SoapRequest*) GetCountryList: (id <SoapDelegate>) handler UserId: (NSNumber *) UserId;
- (SoapRequest*) GetCountryList: (id) _target action: (SEL) _action  UserId: (NSNumber *) UserId;

- (SoapRequest*) GetCurrencyList: (id) _target action: (SEL) _action  UserId: (NSNumber *) UserId ;
- (SoapRequest*) GetCurrencyList: (id <SoapDelegate>) handler  UserId: (NSNumber *) UserId ;


	/* Returns NSMutableArray*.  */
	- (SoapRequest*) GetStateList: (id <SoapDelegate>) handler UserId: (NSNumber *) UserId;
	- (SoapRequest*) GetStateList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;

	/* Returns NSMutableArray*.  */
- (SoapRequest*) GetExpenseTypeList: (id <SoapDelegate>) handler  UserId: (NSNumber *) UserId ;
- (SoapRequest*) GetExpenseTypeList: (id) _target action: (SEL) _action  UserId: (NSNumber *) UserId;
//	- (SoapRequest*) GetExpenseTypeList: (id <SoapDelegate>) handler;
//	- (SoapRequest*) GetExpenseTypeList: (id) target action: (SEL) action;

	/* Returns int.  */
	- (SoapRequest*) logOn: (id <SoapDelegate>) handler username: (NSString*) username password: (NSString*) password;
	- (SoapRequest*) logOn: (id) target action: (SEL) action username: (NSString*) username password: (NSString*) password;

	/* Returns NSDecimalNumber*.  */
	- (SoapRequest*) GetMileage: (id <SoapDelegate>) handler id: (int) _id;
	- (SoapRequest*) GetMileage: (id) target action: (SEL) action id: (int) _id;
- (SoapRequest*) GetMileageData: (id) _target action: (SEL) _action userId: (int) userid;

/*Returns NSDecimalNumber*/
- (SoapRequest*) GetMaxLength: (id <SoapDelegate>) handler id: (NSString *) _id UserId: (NSNumber *) UserId;
- (SoapRequest*) GetMaxLength: (id) _target action: (SEL) _action id: (NSString *) _id UserId: (NSNumber *) UserId;

- (SoapRequest*) AllowJobAddition: (id <SoapDelegate>) handler id: (NSString *) _id UserId: (NSNumber *) UserId;
- (SoapRequest*) AllowJobAddition: (id) _target action: (SEL) _action id: (NSString *) _id UserId: (NSNumber *) UserId;

- (SoapRequest*) ShowJobAsTextField: (id <SoapDelegate>) handler id: (NSString *) _id UserId: (NSNumber *) UserId;
- (SoapRequest*) ShowJobAsTextField: (id) _target action: (SEL) _action id: (NSString *) _id UserId: (NSNumber *) UserId;

	/* Returns NSString*.  */
//	- (SoapRequest*) GetLastName: (id <SoapDelegate>) handler id: (int) _id UserId: (NSNumber *) UserId;
//	- (SoapRequest*) GetLastName: (id) target action: (SEL) action id: (int) _id UserId: (NSNumber *) UserId;

    /* Returns NSMutableArray*.  */
    - (SoapRequest*) GetPayMethodList: (id <SoapDelegate>) handler UserId: (NSNumber *) UserId;
    - (SoapRequest*) GetPayMethodList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;

/* Returns NSMutableArray of City PerDiem */
- (SoapRequest*) GetCityListWithPerDiemList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;
- (SoapRequest*) GetViolationsList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;
- (SoapRequest*) GetExpTypeViolationsMappingList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;
- (SoapRequest*) GetReportStatus: (id) target action: (SEL) action UserId: (NSNumber *) UserId withReportId:(NSNumber *) reportID;


/* Returns NSMutableArray*.  */
- (SoapRequest*) GetConfigLablesInfo: (id <SoapDelegate>) handler id: (int) _id;
- (SoapRequest*) GetConfigLablesInfo: (id) _target action: (SEL) _action id: (int) _id;

/* Returns NSMutableArray*.  */
- (SoapRequest*) GetApplicationConfigLables: (id <SoapDelegate>) handler id: (int) _id UserId: (NSNumber *) UserId;
- (SoapRequest*) GetApplicationConfigLables: (id) _target action: (SEL) _action id: (int) _id UserId: (NSNumber *) UserId;

/*GetJobList returns NSMutableArray */
- (SoapRequest*) GetJobList: (id <SoapDelegate>) handler UserId: (NSNumber *) UserId;
- (SoapRequest*) GetJobList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;

/*GetClassList returns NSMutableArray */
- (SoapRequest*) GetClassList: (id <SoapDelegate>) handler UserId: (NSNumber *) UserId;
- (SoapRequest*) GetClassList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;

/*Get Customer Project Mapping*/
- (SoapRequest*) GetCustomerMappingProjectList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;
- (SoapRequest*) GetJobTaskList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;
- (SoapRequest*) GetBillingCodeList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;

- (SoapRequest*) GetTaxRateList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;
- (SoapRequest*) GetProjectExpenseList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;


- (SoapRequest*) GetAllowVendorAddition: (id <SoapDelegate>) handler UserId: (NSNumber *) UserId;
- (SoapRequest*) GetAllowVendorAddition: (id) target action: (SEL) action UserId: (NSNumber *) UserId;

/* Returns NSDecimalNumber*/
- (SoapRequest*) GetCurrencyRate: (id <SoapDelegate>) handler currencyId: (int) currencyId expenseDate: (NSDate*) expenseDate UserId: (NSNumber *) UserId;
- (SoapRequest*) GetCurrencyRate: (id) _target action: (SEL) _action currencyId: (int) currencyId expenseDate: (NSDate *)expenseDate UserId: (NSNumber *) UserId;

 	+ (SDZService_Mobile*) service;
	+ (SDZService_Mobile*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password;

// Returns NSMutableArray*
/*  */
- (SoapRequest*) GetUnSubmitedBankTranx: (id <SoapDelegate>) handler day: (NSNumber *) day source: (NSString*) source UserId: (NSNumber *) UserId;
- (SoapRequest*) GetUnSubmitedBankTranx: (id) target action: (SEL) action day: (NSNumber *) day source: (NSString*) source UserId: (NSNumber *) UserId;

- (SoapRequest*) GetReportTypeList: (id) _target action: (SEL) _action  UserId: (NSNumber *) UserId;
- (SoapRequest*) GetReportTypeList: (id <SoapDelegate>) handler  UserId: (NSNumber *) UserId;

- (SoapRequest*) GetHeaderConfigLabelsInfo: (id) _target action: (SEL) _action  travelTypeId: (NSNumber *) travelTypeId UserId: (NSNumber *) UserId;

-(SoapRequest *)GetExpenseTransactionPolicyLimt : (id <SoapDelegate>) handler UserId: (NSNumber *) UserId ;
- (SoapRequest*) GetExpenseTransactionPolicyLimt: (id) _target action: (SEL) _action UserId: (NSNumber *) UserId ;

- (SoapRequest*) CreateAndSubmitExpenseReport: (id <SoapDelegate>) handler UserId: (NSNumber *)UserId ReportName:(NSString *)ReportName ReportTypeId:(NSNumber *)ReportTypeId StartDate:(NSDate *)StartDate EndDate:(NSDate *)EndDate ProjectNumber:(NSNumber *)ProjectNumber NetworkNumber:(NSNumber *)NetworkNumber     ReferenceNumber:(NSNumber *)ReferenceNumber CashAdvance:(NSDecimalNumber *)CashAdvance comments:(NSString *)comments ExpenseTransactions:(NSString *)ExpenseTransactions  AddComments:(NSString *)AddComments;

- (SoapRequest*) CreateAndSubmitExpenseReport: (id) _target action: (SEL) _action UserId: (NSNumber *)UserId ReportName:(NSString *)ReportName ReportTypeId:(NSNumber *)ReportTypeId StartDate:(NSDate *)StartDate EndDate:(NSDate *)EndDate ProjectNumber:(NSNumber *)ProjectNumber NetworkNumber:(NSNumber *)NetworkNumber     ReferenceNumber:(NSNumber *)ReferenceNumber CashAdvance:(NSDecimalNumber *)CashAdvance comments:(NSString *)comments ExpenseTransactions:(NSString *)ExpenseTransactions  AddComments:(NSString *)AddComments ;

// save report functionality will add on this additional parameter.
- (SoapRequest*) CreateAndSubmitExpenseReport: (id) _target action: (SEL) _action UserId: (NSNumber *)UserId ReportName:(NSString *)ReportName ReportTypeId:(NSNumber *)ReportTypeId StartDate:(NSDate *)StartDate EndDate:(NSDate *)EndDate ProjectNumber:(NSNumber *)ProjectNumber NetworkNumber:(NSNumber *)NetworkNumber     ReferenceNumber:(NSNumber *)ReferenceNumber CashAdvance:(NSDecimalNumber *)CashAdvance comments:(NSString *)comments ExpenseTransactions:(NSString *)ExpenseTransactions  AddComments:(NSString *)AddComments withAllocationsDict:(NSArray *)allocationsList withExpenseId:(NSNumber *)expenseID withAction:(NSString*)action withReceiptPath:(NSString *)receiptPath;

- (SoapRequest*) getMileageAddressList: (id <SoapDelegate>) handler id: (int) _id UserId: (NSNumber *) UserId;
- (SoapRequest*) getMileageAddressList: (id) _target action: (SEL) _action id: (int) _id UserId: (NSNumber *) UserId;

- (SoapRequest*) getMileageMatrixList: (id <SoapDelegate>) handler id: (int) _id UserId: (NSNumber *) UserId;
- (SoapRequest*) getMileageMatrixList: (id) _target action: (SEL) _action id: (int) _id UserId: (NSNumber *) UserId;

#pragma mark - Cost Allocation
- (SoapRequest*) getCostAccountingsList: (id <SoapDelegate>) handler id: (int) _id UserId: (NSNumber *) UserId;
- (SoapRequest*) getCostAccountingsList: (id) _target action: (SEL) _action id: (int) _id UserId: (NSNumber *) UserId;

- (SoapRequest*) getCostCentersList: (id <SoapDelegate>) handler id: (int) _id UserId: (NSNumber *) UserId;
- (SoapRequest*) getCostCentersList: (id) _target action: (SEL) _action id: (int) _id UserId: (NSNumber *) UserId;

- (SoapRequest*) getBusinessUnitsList: (id <SoapDelegate>) handler id: (int) _id UserId: (NSNumber *) UserId;
- (SoapRequest*) getBusinessUnitsList: (id) _target action: (SEL) _action id: (int) _id UserId: (NSNumber *) UserId;

- (SoapRequest*) getCostCompaniesList: (id <SoapDelegate>) handler id: (int) _id UserId: (NSNumber *) UserId;
- (SoapRequest*) getCostCompaniesList: (id) _target action: (SEL) _action id: (int) _id UserId: (NSNumber *) UserId;

- (SoapRequest*) GetMaxLength: (id <SoapDelegate>) handler id: (NSString *) _id  UserId: (NSNumber *) UserId;


- (SoapRequest*) submitCostAccountingsList:(id <SoapDelegate>)handler action:(SEL)_action allocationsList:(NSArray *)allocationsList UserId:(NSNumber *)UserId;
- (SoapRequest*) getCostCentersList:(id <SoapDelegate>) handler id:(int) _id UserId:(NSNumber *) UserId;

//- (SoapRequest*) submitCostAccountingsList:(id <SoapDelegate>) handler action: (SEL) _action allocationsList : (NSArray *)allocationsList UserId: (NSNumber *) UserId;
- (SoapRequest*) submitAssignCostAllocation:(id) _target  action:(SEL)_action allocationsList:(NSArray *)allocationsList withUserId:(NSNumber *)userId;

- (SoapRequest*) UploadFileForReceipt: (id) _target action: (SEL) _action Data: (NSData*) Data UploadFolder: (NSString *)UploadFolder fileFormat:(NSString *)fileFormat withExpenseObj:(NSManagedObject*)expenseobj;

- (SoapRequest*) GetOCRProcessingStatus:  (id) _target  action: (SEL) _action withFileID:(NSString *) fileID withExpenseObj:(NSManagedObject*)expenseObj;
- (SoapRequest*) GetOCRResult:  (id) _target  action: (SEL) _action withFileID:(NSString *) fileID withExpenseObj:(NSManagedObject*)expenseObj;

- (SoapRequest*) DeleteExpenses:  (id) _target  action: (SEL) _action withExpenseObj:(NSString*)expenseObj UserId:(NSNumber *) UserId;

- (SoapRequest*) GetStaffMemberList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;
- (SoapRequest*) GetApproverList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;
- (SoapRequest*) GetBusinessActivityList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;
- (SoapRequest*) GetReferenceList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;

//
#pragma mark - UserDefaultSync
#pragma mark -

- (SoapRequest*) UserDefaultSync: (id) target action: (SEL) action UserId: (NSNumber *) UserId;
- (SoapRequest*) SaveUserDefaultSync: (id) target action: (SEL) action UserId: (NSNumber *) UserId withDictionary:(NSDictionary *)dict;
- (SoapRequest*) TimesheetUserDefaultSync: (id) target action: (SEL) action UserId: (NSNumber *) UserId;
- (SoapRequest*) SaveTimeSheetUserDefaultSync: (id) target action: (SEL) action UserId: (NSNumber *) UserId withDictionary:(NSDictionary *)dict;
//

#pragma mark - Timesheet WS
#pragma mark -
- (SoapRequest*) GetTimeSheetTodoList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;
- (SoapRequest*) GetConfigLablesInfoTimeSheet: (id <SoapDelegate>) handler id: (int) _id;
- (SoapRequest*) GetConfigLablesInfoTimeSheet: (id) _target action: (SEL) _action id: (int) _id;
- (SoapRequest*) GetTimeSheetTypeList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;


- (SoapRequest*) SubmitTimesheets : (id) _target  action: (SEL) _action timesheetList:(NSArray *)timesheetList withUserId : (NSNumber *)userId;
- (SoapRequest*) GetTimeSheetDetail: (id) target action: (SEL) action UserId: (NSNumber *) UserId headerId:(NSString*)headerId;
- (SoapRequest*) SubmitTimeSheetDetail: (id) target action: (SEL) action UserId: (NSNumber *) UserId headerId:(NSString*)headerId;
- (SoapRequest*) GetTimeSheetStatus: (id) target action: (SEL) action UserId: (NSNumber *) UserId withTSHeaderId:(NSNumber *) headerId;


//

#pragma mark - UnApproved Reports
#pragma mark -

- (SoapRequest*) GetUnApprovedReportsList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;
- (SoapRequest*) AcceptReports: (id) target action: (SEL) action UserId: (NSNumber *) UserId withExpenseID:(NSNumber *) expenseID withOtherRemarks:(NSString *)remarks;
- (SoapRequest*) RejectReports: (id) target action: (SEL) action UserId: (NSNumber *) UserId withExpenseID:(NSNumber *) expenseID withOtherRemarks:(NSString *)remarks;
- (SoapRequest*) GetUnApprovedReportsDetails: (id) target action: (SEL) action UserId: (NSNumber *) UserId reportID:(NSNumber *) reportID;

//

#pragma mark - Cost Allocations HCP Details
#pragma mark -

- (SoapRequest*) GetHCPDetails: (id) target action: (SEL) action UserId: (NSNumber *) UserId withDictionary:(NSDictionary *)dict;
- (SoapRequest*) GetLicenceStateList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;
- (SoapRequest*) GetProfessionalDesignationList: (id) target action: (SEL) action UserId: (NSNumber *) UserId;

//

#pragma mark - Reports Sync
#pragma mark -

- (SoapRequest*) GetUnSubmittedReports: (id) target action: (SEL) action UserId: (NSNumber *) UserId;
- (SoapRequest*) GetUnSubmittedReportsDetails: (id) target action: (SEL) action UserId: (NSNumber *) UserId ExpenseId:(NSNumber *)expenseId;

//

#pragma mark - Budget Feature
#pragma mark -

- (SoapRequest*) getBudgetByExpenseType: (id) target action: (SEL) action UserId: (NSNumber *) UserId withExpenseType:(NSManagedObject *) expenseObj;
- (SoapRequest*) getBudgetByProject: (id) target action: (SEL) action UserId: (NSNumber *) UserId withExpenseType:(NSManagedObject *) expenseObj;

//

#pragma mark - Cash Advance
#pragma mark -

- (SoapRequest*) GetRemainingCashAdvance: (id) target action: (SEL) action UserId: (NSNumber *) UserId;

//

#pragma mark - Reset Password
#pragma mark -

- (SoapRequest*) GetResetPassword: (id) target action: (SEL) action UserId: (NSString *) UserId;

//

#pragma mark - Change Password
#pragma mark -

- (SoapRequest*) GetChangePassword: (id) target action: (SEL) action UserId: (NSDictionary *) Dict;

//

#pragma mark - Get Service URL
#pragma mark -

- (SoapRequest*) GetServiceURL: (id) _target action: (SEL) _action username: (NSString*) username;

//

#pragma mark - Get Receipt Path URL with Signature
#pragma mark -

- (SoapRequest*) GetServiceReceiptURLWithSignature: (id) _target action: (SEL) _action userID : (NSNumber *) UserId ReceiptPath:(NSString *) ReceiptPath;

@end
	
